site_name: WebDev Learning Resources
theme: material
# favicon: favicon.png
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
copyright: Copyright &copy; 2021 Dainius T.
repo_url: https://github.com/dainiuxt/kb